# Base image for RHEL8 tests.
FROM registry.access.redhat.com/ubi8:8.0
# Not sure these instructions shouldn't be part of the cookbook.
RUN mkdir /etc/sudoers.d
RUN yum install -y yum-utils
# Container must have an always active process to stay alive.
ENTRYPOINT /bin/bash -c trap exit 0 SIGTERM; while :; do sleep 1; done
