name: ParallelCluster Cookbook CI

on: [push, pull_request]

jobs:
  ec2-validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        os:
          - redhat8
      fail-fast: false
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::472648941662:role/my-github-actions-role
          role-session-name: MySessionName
          aws-region: us-east-1
          audience: sts.amazonaws.com
      - name: Check out code
        uses: actions/checkout@main
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: Test-Kitchen
        uses: actionshub/test-kitchen@main
        with:
          os: ${{ matrix.os }}
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_YAML: kitchen.ec2.yml
          KITCHEN_LOCAL_YAML: kitchen.validate.yml
          KITCHEN_GLOBAL_YAML: kitchen.global.yml
        continue-on-error: false
